### ISSUE TITLE
Create account with custom private key

### ISSUE THREAD

**Issue by 7flash** [LimeChain/eoslime#31]
Currently, AccountFactory provides createFromName and createRandom methods, both of them generate random keys for newly created account.

In some cases, we need to create an account with development private key we know in advance.

For example, in contracts accepting payments, token account name is defined in header file, and therefore it always should be the same. When testing such contract, we load account with existing name given private key from account. When running this test first time, account does not exist, and we need to create it with the same private key that will be used when running further tests.

Please, let me know if there are any other suggestions about specific case described above.

**Comment by bakasura980** [comment]
Hey @7flash, If I am understanding your question properly, you have your private key in advance, and you have a hardcoded name in your contract, but this name does not exist yet. So you need to have a function such as createFromName and to have the possibility to provide a private key also?

**Comment by 7flash** [comment]
@bakasura980 Yes

For example, yesterday I created a smart contract using eoslime: eosio-hours-tracker

In this case, I need to deploy token always to the same address, - so I create account when running test first time, and relay on already created account when running tests next times during development process

Since there is no opportunity to pass private key to createFromName method, I implemented alternative approach, - that is storing private key in temporary file between running tests: 
https://github.com/7flash/eosio-hours-tracker/blob/2c8607b458fed507353fa4119ac71f40d5e80c2b/test/hourstracker.test.js#L39

I think it would be better to pass constant development private key instead of storing it in file

Please let me know if there is any better approach to this process

**Comment by bakasura980** [comment]
Hey @7flash 
At the moment eoslime creates accounts, but you should store them manually somewhere. Actually this is a great idea for a CLI command, but it would be implemented after 1/2 months because at the moment we are preparing for v1.0.0

For your case, I have the following suggestion:
*  Make a test-purpose contract - `eosio-hours-tracker-test.cpp`
*  Copy and paste the code from your original one but change the following
*  In your `withdraw` method, provide a token name as a parameter(string)
At this line
https://github.com/7flash/eosio-hours-tracker/blob/2c8607b458fed507353fa4119ac71f40d5e80c2b/src/hourstracker.cpp#L75
change the hardcoded name with the one of your token provided in the function

In this way, you will be able actually to deploy each time both contracts - token and eosio-trackect without keeping private keys. You will be able to test your contract behavior exactly, just the token name will be dynamically provided

Please, tell me how do you feel about it ?

**Comment by 7flash** [comment]
@bakasura980 Can we make this process automated?

**Comment by bakasura980** [comment]
@7flash Do you have an idea?
